version: '3'

services:
  mysql-db-inventory:
    image: mariadb:10.6
    container_name: mysql-db-inventory
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: inventory-db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      PMA_HOST: mysql-db-inventory
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - '8889:8888'
    expose:
      - '8888'
    environment:
      - DB_URL=jdbc:mysql://mysql-db-inventory:3306/inventory-db


volumes:
  mysql_data:
